In [1]:
import numpy as np

array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])

#sum 2 arrays
sum = array1+array2
print(sum)

[ 7  9 11 13 15]


In [2]:
subtract = array1-array2
print(subtract)

[-5 -5 -5 -5 -5]


In [3]:
multiply=array1*array2
print(multiply)

[ 6 14 24 36 50]


In [4]:
div=array1/array2
print(div)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [6]:
mean=np.mean(array1)
print(mean)

mean2=np.mean(array2)
print(mean2)

3.0
8.0


In [7]:
sum=np.sum(array1)
print(sum)

sum2=np.sum(array2)
print(sum2)

15
40


In [11]:
max=np.max(array1)
max2=np.max(array2)
print("max array1: ",max,"\nmax array2: ",max2)

min=np.min(array1)
min2=np.min(array2)
print("min array1: ",min,"\nmin array2: ",min2)

max array1:  5 
max array2:  10
min array1:  1 
min array2:  6


In [14]:
greater_than = array1>2
print("greater than: ",greater_than)

less_than = array1<2
print("less than: ",less_than)

greater than:  [False False  True  True  True]
less than:  [ True False False False False]


In [19]:
#adding num to all values in the array
result=array1+5
print(result)

[ 6  7  8  9 10]
