In [1]:
import numpy as np

num=[1,2,3,4,5]

array1=np.array(num)
print(array1)

[1 2 3 4 5]


In [3]:
zero_array=np.zeros(5)
print(zero_array)

[0. 0. 0. 0. 0.]


In [5]:
one_array=np.ones(3)
print(one_array)

[1. 1. 1.]


In [9]:
#from 1 to 10, per 2
range_array=np.arange(1,10,2)
print(range_array)

[1 3 5 7 9]


In [11]:
#from 1 to 100, fetch 5
random_array=np.random.randint(1,100,5)
print(random_array)

[ 2 76 75 58 89]


In [15]:
#2 rows 3 cols
random_matrix=np.random.rand(2,3)
print(random_matrix)

[[0.04551218 0.99411344 0.70830113]
 [0.76099495 0.8148707  0.19872917]]


In [16]:
#from the range_array above
shape=range_array.shape
print(shape)

(5,)


In [17]:
size=range_array.size
print(size)

5


In [18]:
dtype=range_array.dtype
print(dtype)

int64


In [22]:
#dimension of array
print(range_array.ndim)

1
