In [1]:
import numpy as np

array1=np.array([10,20,30,40,50])

secondelement=array1[1]

print(secondelement)

20


In [2]:
#from the last
print(array1[-2])

40


In [7]:
#sliced array
#from index upto next position (not index)

sliced_arr=array1[1:4]
print(sliced_arr)

[20 30 40]


In [8]:
#from the first element, every 2nd element
step_array=array1[::2]
print(step_array)

[10 30 50]


In [16]:
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

#row index and col index
element=matrix[1,1]
print(element)

5


In [17]:
#get specific row from matrix

#: means needs the entire row
#from row index
second_row=matrix[1,:]
print(second_row)

[4 5 6]


In [18]:
#get specific col from matrix

#[<row>,<col>] - : means entire row/col
second_col=matrix[:,1]
print(second_col)

[2 5 8]


In [20]:
#data management
#missing values (Nan)

data=np.array([1,2,3,np.nan,4,5])

#check missing data
missing = np.isnan(data)
print(missing)

[False False False  True False False]


In [21]:
#fill missing number

data_fill=np.nan_to_num(data, nan=100)
print(data_fill)

[  1.   2.   3. 100.   4.   5.]
